url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Atlas Learning Solutions" 
description: "Lorem ipsum dolor sit amet"

linkedin: atlas-lb

collections:
  courses:
    output: true